### PR TITLE
Add Support for YouTube Auto-Generated Music (eg. YT-Music songs)

### PR DESCRIPTION
**Pull request by zLeqitEclipse**
Please dont judge me by my coding style (yes, it could be improved)

This PR adds the functionality to use YT-Music Songs (YouTube Auto Generated Videos) to dynamically fetch the Song Metadata, using the Video Description. (eg. https://youtu.be/Xp4IidJnxMw)

Instead of trying to use the Video Title to fetch author, song title etc. we can use the Video Description to fetch more Information and fit it into the File Metadata. 

If the Video that has been input is a regular YouTube Video (identified by the "Auto-generated by YouTube." in the description) it will fallback to the default tagging process.

### CODE REVIEW

**Comment by shaked6540** [comment]
Hey! Thanks for this pull request. 

Maybe I missed something, but where do you call the new function (TagMusicFile) that you added?
I also don't see where you're checking if "Auto-generated by YouTube." is in the description

Did you forget to add it, or did you want me to add these checks?

**Comment by zLeqitEclipse** [comment]
> Hey! Thanks for this pull request. 
> 
> 
> 
> Maybe I missed something, but where do you call the new function (TagMusicFile) that you added?
> 
> I also don't see where you're checking if "Auto-generated by YouTube." is in the description
> 
> 
> 
> Did you forget to add it, or did you want me to add these checks?


Take a look at l. 379. I just put the check into the old TagFile Task. Idk if that's a problem, it at least didn't cause any issues while I was debugging and stress testing (playlist download with 30+ songs)

**Comment by shaked6540** [comment]
Oh yeah, my bad, I see it now

I'll test it too tomorrow and if it works I'll approve and release a new version :) 

Thanks again

**Comment by zLeqitEclipse** [comment]
I've just implemented a function which cuts the images to an 4:3 aspect ratio (just like how they are supposed to) 

Before: 
Yad (Sped Up)

After:
Yad (Sped Up) cropped

**Comment by shaked6540** [comment]
I'll try to take a look at it tonight, I might only have time to check it after the weekend. From what i've read online the cover picture should have the same width and height, while the pictures we get from youtube are usually not the same width and height (they're usually 1280x720), so that might be reason why you're seeing the bars

**Comment by zLeqitEclipse** [comment]
Okay, i don't know how to say this, but it apparently works now, with me absolutely changing nothing in the code. I've downloaded multiple Playlists and Songs and it works flawlessly. So that means, that the commit, which i've pushed, is actually rather finished then unfinished, and should be ready to merge in that state...

**Comment by shaked6540** [comment]
Any more commits before I merge this?

**Comment by zLeqitEclipse** [comment]
Nope, this PR is ready to merge.

**Comment by shaked6540** [comment]
I'll release this later tonight, for now its merged :)

**Pull request merged**
